services:
  - type: web
    name: repairwale-server
    env: node
    plan: free
    autoDeploy: true
    buildCommand: |
      cd repairwale/client
      npm ci
      npm run build
      cd ../server
      npm ci
    startCommand: bash -c "cd repairwale/server && node index.js"
